# This file was generated by GoReleaser. DO NOT EDIT.
cask "homepki" do
  version "0.2.2"

  on_macos do
    on_intel do
      url "https://github.com/bcollard/homepki/releases/download/v#{version}/homepki_#{version}_darwin_amd64.tar.gz"
      sha256 "acc910db03b27cb6453d75e22ef825cc982edb66997c995fcde0b6f82dd1af05"
    end
    on_arm do
      url "https://github.com/bcollard/homepki/releases/download/v#{version}/homepki_#{version}_darwin_arm64.tar.gz"
      sha256 "377eb769d9bdb104b7996b5a4f674ac3786706752df6aa62d43493541950c1de"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bcollard/homepki/releases/download/v#{version}/homepki_#{version}_linux_amd64.tar.gz"
      sha256 "f1b8893ab9a57f40c3194dae6c5e9a35e5993ae5e99ea7826937c3752e291e88"
    end
    on_arm do
      url "https://github.com/bcollard/homepki/releases/download/v#{version}/homepki_#{version}_linux_arm64.tar.gz"
      sha256 "d14bcdc2fbf39cfbf5fbf70f12304e96517b1f1d4712eabb4bfae199617c86ba"
    end
  end

  name "homepki"
  desc "A simple PKI management tool for local development"
  homepage "https://github.com/bcollard/homepki"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "homepki"

  # No zap stanza required

end
