# This file was generated by GoReleaser. DO NOT EDIT.
cask "homepki" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "bdfa97b7f9f689573de12f4ede19d6cab7ca48ce04ccffe284d1fd3a74f85889"
      url "https://github.com/bcollard/homepki/releases/download/v#{version}/homepki_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2cc69adf6173c826f9b20f5e9235d1b0a0920e03c3e86489b9e0aaecbefbbe7e"
      url "https://github.com/bcollard/homepki/releases/download/v#{version}/homepki_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "012fd9229dd949cc7d7a3d9299702a6e4e7bd013199da473bddbfccd4af75722"
      url "https://github.com/bcollard/homepki/releases/download/v#{version}/homepki_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "10464b30ac6b170e7f5a8ea1e76b34941a47c3505aabd78854d84a330386e142"
      url "https://github.com/bcollard/homepki/releases/download/v#{version}/homepki_#{version}_linux_amd64.tar.gz"
    end
  end

  name "homepki"
  desc "A simple PKI management tool for local development"
  homepage "https://github.com/bcollard/homepki"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "homepki"

  # No zap stanza required
end
