# This file was generated by GoReleaser. DO NOT EDIT.
cask "homepki" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "32b79a27ea0a1ed698ff7c679f73958742f45a4e5ee68f4d53327a0b7f156721"
      url "https://github.com/bcollard/homepki/releases/download/v#{version}/homepki_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "35ef88985c74458abd20797f58ee895ccaef87c394fd012988c6fe134d0afbba"
      url "https://github.com/bcollard/homepki/releases/download/v#{version}/homepki_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b1bc0adb32999918167149fa1d684f8979169c2d6114422eeefb9add73e32a4d"
      url "https://github.com/bcollard/homepki/releases/download/v#{version}/homepki_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a227d830f694edd65b6c35dd120cb1035f477f1e7b22e408dd647807362412f2"
      url "https://github.com/bcollard/homepki/releases/download/v#{version}/homepki_#{version}_linux_amd64.tar.gz"
    end
  end

  name "homepki"
  desc "A simple PKI management tool for local development"
  homepage "https://github.com/bcollard/homepki"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "homepki"

  # No zap stanza required
end
