# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Homepki < Formula
  desc "A simple PKI management tool for local development"
  homepage "https://github.com/bcollard/homepki"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bcollard/homepki/releases/download/v0.1.6/homepki_Darwin_x86_64.tar.gz"
      sha256 "a70892f1dc8d3e3a4c251afcfedd0c4cf964bcc5bf49316b3cc313f0350ac255"

      def install
        bin.install "homepki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bcollard/homepki/releases/download/v0.1.6/homepki_Darwin_arm64.tar.gz"
      sha256 "741f0f348410a298c16d2e0f92bb90d6bb884509013fb09fcbc7f349465157b7"

      def install
        bin.install "homepki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bcollard/homepki/releases/download/v0.1.6/homepki_Linux_x86_64.tar.gz"
      sha256 "f3c55539b56ffb43561cffdbf707f5802b366bacb4ad325b06d12b86da5180c6"
      def install
        bin.install "homepki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bcollard/homepki/releases/download/v0.1.6/homepki_Linux_arm64.tar.gz"
      sha256 "02ab0862fd689193632cf8595ab2fae7c13fe630491d7d78080c2800e33b01c1"
      def install
        bin.install "homepki"
      end
    end
  end
end
